# Generated by Django 5.2.4 on 2025-09-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0006_remove_menuitem_inventory_menuitem_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='menuitem_id',
            field=models.SmallIntegerField(default=1),
        ),
    ]
